### ISSUE TITLE
test failures with 4.8.7 with GH-1216 attributes specs

### ISSUE THREAD

**Issue by boutil** [nanoc/nanoc#1219]
Hi!

When trying to build 4.8.7 for Debian, I got the following test failures from executing `rake spec`:
```
Progress: |==============================================================

  1) GH-1216 attributes changed using #[]= changes output file
     Failure/Error:
       expect { Nanoc::CLI.run(%w[compile]) }
         .to change { File.read('output/talks.html') }
         .from('A= B=')
         .to('A=archived B=archived')

       expected result to have initially been "A= B=", but was "B= A="
     # ./spec/nanoc/regressions/gh_1216_spec.rb:38:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:52:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:30:in `block (4 levels) in <top (required)>'
     # ./lib/nanoc/spec.rb:10:in `chdir'
     # ./spec/spec_helper.rb:30:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:24:in `block (2 levels) in <top (required)>'

Progress: |==============================================================

  2) GH-1216 attributes changed using update_attributes changes output file
     Failure/Error:
       expect { Nanoc::CLI.run(%w[compile]) }
         .to change { File.read('output/talks.html') }
         .from('A= B=')
         .to('A=archived B=archived')

       expected result to have initially been "A= B=", but was "B= A="
     # ./spec/nanoc/regressions/gh_1216_spec.rb:61:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:52:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:30:in `block (4 levels) in <top (required)>'
     # ./lib/nanoc/spec.rb:10:in `chdir'
     # ./spec/spec_helper.rb:30:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:24:in `block (2 levels) in <top (required)>'

Progress: |==============================================================

  3) GH-1216 raw content changed changes output file
     Failure/Error:
       expect { Nanoc::CLI.run(%w[compile]) }
         .to change { File.read('output/talks.html') }
         .from('A= B=')
         .to('AAH=archived B=current')

       expected result to have initially been "A= B=", but was "B= A="
     # ./spec/nanoc/regressions/gh_1216_spec.rb:85:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:52:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:30:in `block (4 levels) in <top (required)>'
     # ./lib/nanoc/spec.rb:10:in `chdir'
     # ./spec/spec_helper.rb:30:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:24:in `block (2 levels) in <top (required)>'

Progress: |====================================================================|

Finished in 26.29 seconds (files took 1.22 seconds to load)
2133 examples, 3 failures

Failed examples:

rspec ./spec/nanoc/regressions/gh_1216_spec.rb:37 # GH-1216 attributes changed using #[]= changes output file
rspec ./spec/nanoc/regressions/gh_1216_spec.rb:60 # GH-1216 attributes changed using update_attributes changes output file
rspec ./spec/nanoc/regressions/gh_1216_spec.rb:84 # GH-1216 raw content changed changes output file

/usr/bin/ruby2.3 /usr/bin/rspec --pattern ./spec/\*\*/\*_spec.rb  --exclude-pattern ./spec/nanoc/filters/less_spec.rb -r ./spec/spec_helper.rb --color failed
```
It seems that the expected string "A= B=" is sometimes "B= A=". It is reliably "B= A=" on my machine.

Cédric

**Comment by ddfreyne** [comment]
Oh duh, the test assumes that the filesystem returns files in the order that they were written in, which isn’t always true. Fix coming up.

**Comment by ddfreyne** [comment]
e6d5c6e301eb5cb06f9e397392e68ac219a07bf6 should fix this. I can’t reproduce it locally; can you give it a try for me?

**Comment by boutil** [comment]
With your commit, the tests are passing. Problem solved. Thanks
