### ISSUE TITLE
Crash when calling #raw_path in Rules

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#1228]
In the Rules file, calling `#raw_path` raises a `FiberError`.

### Steps to reproduce

@moll said:

I had code in Rules for conditionally filtering:

```ruby
filter :fingerprint_paths, :type => :css if rep.raw_path =~ /\.css$/
```

erroring with:

```
FiberError: can't yield from root fiber
  0. /usr/local/lib/ruby/gems/2.4.0/gems/nanoc-4.8.9/lib/nanoc/base/views/item_rep_view.rb:84:in `yield'
  1. /usr/local/lib/ruby/gems/2.4.0/gems/nanoc-4.8.9/lib/nanoc/base/views/item_rep_view.rb:84:in `raw_path'
```

### Expected behavior

The raw path is returned

### Actual behavior

`FiberError: can't yield from root fiber`

**Comment by ddfreyne** [comment]
Removing `#raw_path` (#1229) does’t quite work because `#raw_path` has a good use case.
