### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by frankdopomezzanotte** [nanoc/nanoc#1461]
Traceback (most recent call last):
	6: from /Users/frankdopomezzanotte/.rvm/gems/ruby-head/bin/ruby_executable_hooks:10:in `<main>'
	5: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	4: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	3: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	2: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	1: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
/Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require': cannot load such file -- rubygems-bundler/noexec (LoadError)
	10: from /Users/frankdopomezzanotte/.rvm/gems/ruby-head/bin/ruby_executable_hooks:10:in `<main>'
	 9: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
	 8: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
	 7: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
	 6: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	 5: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	 4: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:157:in `rescue in require'
	 3: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:157:in `require'
	 2: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	 1: from /Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
/Users/frankdopomezzanotte/.rvm/rubies/ruby-head/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x00007fbcd7a311c8> (NoMethodError)

**Comment by frankdopomezzanotte** [comment]
i really don't have idea... please why all those errors?

gem update --system
Latest version already installed. Done.
fne-2:~ frankdopomezzanotte$ gem env version
3.1.0.pre2
fne-2:~ frankdopomezzanotte$ bundle --version
Bundler version 2.1.0.pre.2
fne-2:~ frankdopomezzanotte$ rvm --version
rvm 1.29.9 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
fne-2:~ frankdopomezzanotte$ ruby --version
ruby 2.7.0dev (2019-10-22T05:06:45Z trunk 22845176d7) [x86_64-darwin17]

**Comment by frankdopomezzanotte** [comment]
macOS high sierra 10.13.6

**Comment by frankdopomezzanotte** [comment]
nanoc hates me!
