### ISSUE TITLE
guard-nanoc 2.1.8 won't start

### ISSUE THREAD

**Issue by jmstfv** [nanoc/nanoc#1494]
Aloha 👋 

I've hit a small problem with the newest release of nanoc-guard.

### Steps to reproduce

1. Create a new nanoc project: `nanoc create-site booyah && cd booyah/`
1. Install gems from the Gemfile (see below): `bundle install`
2. Run `bundle exec nanoc live --port 3001`
3. 💥 

### Expected behavior

Nanoc + Guard should work as always (works fine when downgrading nanoc to `4.11.14` and guard-nanoc to `2.1.7`)

`bundle exec nanoc view --port 3001` works fine though

### Actual behavior

```
#<Thread:0x00007ffa1aa7a118 ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/guard-nanoc-2.1.8/lib/guard/nanoc/live_command.rb:35 run> terminated with exception (report_on_exception is true):
Captain! We’ve been hit!
~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/guard-nanoc-2.1.8/lib/guard/nanoc/live_command.rb:39:in `block in run'
: NoMethodError: undefined method `start' for #<Class:0x00007ffa1a592a88>::Guard

uninitialized constant #<Class:0x00007ffa1a592a88>::Guard::Nanoc::CLI (  0. ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/guard-nanoc-2.1.8/lib/guard/nanoc/live_command.rb:42:in `run'
  1. ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nanoc-cli-4.11.15/lib/nanoc/cli/command_runner.rb:15:in `block in call'
  2. ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nanoc-cli-4.11.15/lib/nanoc/cli/error_handler.rb:15:in `block in handle_while'
  3. ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nanoc-cli-4.11.15/lib/nanoc/cli/error_handler.rb:57:in `handle_while'
NameError  4. ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nanoc-cli-4.11.15/lib/nanoc/cli/error_handler.rb:15:in `handle_while'
)  5. ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/nanoc-cli-4.11.15/lib/nanoc/cli/command_runner.rb:14:in `call'


Captain! We’ve been hit!

NameError: uninitialized constant #<Class:0x00007ffa1a592a88>::Guard::Nanoc::CLI

  0. ~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/guard-nanoc-2.1.8/lib/guard/nanoc/live_command.rb:39:in `block in run'
```

### Details

Gemfile

```
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'builder', '~> 3.2.4'
gem 'kramdown', '~> 2.1.0'
gem 'nanoc', '~> 4.11.15'
gem 'nokogiri', '~> 1.10.9'

group :development do
  gem 'adsf', '~> 1.4.3'
  gem 'minitest', '~> 5.14.0'
  gem 'rake', '~> 13.0.1'
  gem 'rubocop', '~> 0.80.1', require: false
end

group :nanoc do
  gem 'guard-nanoc', '~> 2.1.8'
end
```

### Crash log

https://gist.github.com/jmstfv/33ccab0e78e806d1fdb0e0fd4f25e5ed

**Comment by ddfreyne** [comment]
Thank you for the detailed bug report! I can reproduce it — it appears that some constant lookup is failing. Fix coming up.

**Comment by ddfreyne** [comment]
Fixed in guard-nanoc 2.1.9, released just now (it might take a few minutes before it shows up in Rubygems).

**Comment by jmstfv** [comment]
It works, thanks!

P.S. Nanoc is truly a joy to work with. Thanks for your awesome work, Denis! 😃
