### ISSUE TITLE
Exception in finalizer: can't be called from trap context

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#1559]
### Steps to reproduce

Run `nanoc` or its tests.

### Expected behavior

No error

### Actual behavior

The following error is shown, though compilation success as normal:

```
2022-01-08T10:57:21.8860000Z /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema/parser.rb:129: warning: Exception in finalizer #<Proc:0x00007f6e1808a5b0 /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/ref-2.0.0/lib/ref/soft_reference.rb:28 (lambda)>
10
/home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/ref-2.0.0/lib/ref/soft_reference.rb:29:in `synchronize': can't be called from trap context (ThreadError)
11
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/ref-2.0.0/lib/ref/soft_reference.rb:29:in `block in <class:SoftReference>'
12
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema/parser.rb:129:in `is_a?'
13
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema/parser.rb:129:in `parse_data'
14
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema/parser.rb:264:in `block in parse_properties'
15
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema/parser.rb:263:in `each'
16
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema/parser.rb:263:in `parse_properties'
17
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema/parser.rb:350:in `parse_schema'
18
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema/parser.rb:140:in `parse_data'
19
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema/parser.rb:33:in `parse'
20
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema/parser.rb:42:in `parse!'
21
	from /home/runner/work/nanoc/nanoc/vendor/bundle/ruby/3.1.0/gems/json_schema-0.21.0/lib/json_schema.rb:29:in `parse!'
22
	from /home/runner/work/nanoc/nanoc/nanoc-core/lib/nanoc/core/configuration.rb:198:in `validate'
23
	from /home/runner/work/nanoc/nanoc/nanoc-core/lib/nanoc/core/configuration.rb:53:in `initialize'
24
	from /home/runner/work/nanoc/nanoc/nanoc-core/lib/nanoc/core/configuration.rb:63:in `new'
25
	from /home/runner/work/nanoc/nanoc/nanoc-core/lib/nanoc/core/configuration.rb:63:in `with_defaults'
```

**Comment by ddfreyne** [comment]
Here’s a single test case that exhibits the problem:

```
cd nanoc-core
bundle exec rspec --format=documentation spec/nanoc/core/identifiable_collection_spec.rb:68
```

```
      context 'frozen' do
        before { identifiable_collection.freeze }

        example do
          expect(identifiable_collection['/one']).to equal(objects[0])
          expect(identifiable_collection['/fifty']).to be_nil
        end
      end
```

It appears that `#freeze` in particular causes this issue.

Will continue investigating.
