### ISSUE TITLE
External link checking can fail with Net::OpenTimeout

### ISSUE THREAD

**Issue by iay** [nanoc/nanoc#1660]
### Steps to reproduce

Use Nanoc's external link checker

### Expected behavior

A list of problems, or not.

### Actual behavior

Some URLs result in a `Net::OpenTimeout` error.

### Details

Ruby 3.2.2, Intel Mac.

I have no idea why the Ruby RFC3986 parser would start throwing `Net::OpenTimeout` errors. I suppose it might conceivably be a regular expression timeout.

I edited `validate` in `external_links.rb` to catch this error as follows:

```ruby
        def validate(href)
          # Parse
          url = nil
          begin
            url = URI.parse(href)
          rescue URI::Error
            return Result.new(href, 'invalid URI')
          rescue Net::OpenTimeout
            return Result.new(href, 'timed out')
          end
```

This allowed me to catch some of the failing URLs, but there's nothing obviously weird about them so I'm at a loss as to the root cause here:

```
https://slfuturesalon.blogs.com/second_life_future_salon/2005/10/thomas_pm_barne.html
https://web.archive.org/web/20070213232517/http://www.cardsforcharity.co.uk/cards/CARDS-FOR-GOOD-CAUSES-BAA-HUMBUG-ARTHRITIS-RESEARCH-CAMPAIGN-ARCA07.htm
https://sectigo.com/knowledge-base/detail/Which-browser-can-I-use-to-signup-for-an-S-MIME-Email-Certificate/kA01N000000zFKX
```

### Crash log

```
/opt/local/lib/ruby3.2/3.2.0/uri/rfc3986_parser.rb:21:in `match': execution expired (Net::OpenTimeout)
        from /opt/local/lib/ruby3.2/3.2.0/uri/rfc3986_parser.rb:21:in `split'
        from /opt/local/lib/ruby3.2/3.2.0/uri/rfc3986_parser.rb:71:in `parse'
        from /opt/local/lib/ruby3.2/3.2.0/uri/common.rb:193:in `parse'
        from /Volumes/Cased/git/iay/systems/site/vendor/ruby/3.2.0/gems/nanoc-checking-1.0.2/lib/nanoc/checking/checks/external_links.rb:49:in `validate'
```

**Comment by denisdefreyne** [comment]
I looked at this a while ago and I’m at a loss -- surely a RFC 3989 parser shouldn’t open network connections?

What is more, the URLs you provided should be absolutely fine.

Grasping at straws, I tried running the parser with my DNS server pointing to a fake host, and it all stills works as expected…
