### ISSUE TITLE
LoadError: cannot load such file -- sass

### ISSUE THREAD

**Issue by GrooveStomp** [nanoc/nanoc#321]
```
↳ nanoc co
Loading site data… done
Compiling site…
        skip  [1371597955.01s]  output/assets/style/_variables.css
        skip  output/assets/style/main.css
        skip  output/index.html

Captain! We’ve been hit!

Message:

LoadError: cannot load such file -- sass
Make sure the gem is added to Gemfile and run `bundle install`.

Compilation stack:

  - [item]   /assets/style/_variables/ (rep default)

Stack trace:

  0. /Users/aoman/.rbenv/versions/1.9.3-p194/gemsets/meta-site-2/gems/nanoc-3.6.4/lib/nanoc/base/compilation/filter.rb:100:in `require'
  1. /Users/aoman/.rbenv/versions/1.9.3-p194/gemsets/meta-site-2/gems/nanoc-3.6.4/lib/nanoc/base/compilation/filter.rb:100:in `block in setup'
  2. /Users/aoman/.rbenv/versions/1.9.3-p194/gemsets/meta-site-2/gems/nanoc-3.6.4/lib/nanoc/base/compilation/filter.rb:100:in `each'
  3. /Users/aoman/.rbenv/versions/1.9.3-p194/gemsets/meta-site-2/gems/nanoc-3.6.4/lib/nanoc/base/compilation/filter.rb:100:in `setup'
  4. /Users/aoman/.rbenv/versions/1.9.3-p194/gemsets/meta-site-2/gems/nanoc-3.6.4/lib/nanoc/base/compilation/filter.rb:121:in `setup_and_run'
  5. /Users/aoman/.rbenv/versions/1.9.3-p194/gemsets/meta-site-2/gems/nanoc-3.6.4/lib/nanoc/base/result_data/item_rep.rb:344:in `filter'
  6. /Users/aoman/.rbenv/versions/1.9.3-p194/gemsets/meta-site-2/gems/nanoc-3.6.4/lib/nanoc/base/compilation/item_rep_proxy.rb:47:in `filter'
  7. /Users/aoman/.rbenv/versions/1.9.3-p194/gemsets/meta-site-2/gems/nanoc-3.6.4/lib/nanoc/base/compilation/rule_context.rb:55:in `filter'
  8. ./Rules:17:in `block in load'
  9. /Users/aoman/.rbenv/versions/1.9.3-p194/gemsets/meta-site-2/gems/nanoc-3.6.4/lib/nanoc/base/compilation/rule.rb:68:in `instance_eval'
  ... 26 more lines omitted. See full crash log for details.

If you believe this is a bug in nanoc, please do report it at
-> https://github.com/nanoc/nanoc/issues/new <-

A detailed crash log has been written to ./crash.log.
```

Here's my crash.log: https://gist.github.com/GrooveStomp/5810442

Here's my Rules file: https://gist.github.com/GrooveStomp/5810447

Ruby version: 1.9.3-p194
Nanoc version: 3.6.4

And my Gemfile:

``` Ruby
source 'https://rubygems.org'

gem 'nanoc'
gem 'adsf'
gem 'haml'
gem 'sass'
```

**Comment by dtenenba** [comment]
I experienced this issue (with pry as well as sass) and fixed it by removing the ruby I was running (`rbenv uninstall 2.1.1`) then reinstalling it (`rbenv install 2.1.1`) and then reinstalling bundler and reinstalling my gems with `bundle install`.
