### ISSUE TITLE
Invalid multibyte character error when not using UTF-8 on JRuby

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#340]
As explained in #335:

nanoc 3.6.5 on JRuby:

```
Captain! We've been hit!

Message:

RegexpError: invalid multibyte character: /â¦/

Compilation stack:

  (empty)

Stack trace:

  0. org/jruby/RubyString.java:3099:in `gsub'
  1. org/jruby/RubyString.java:3067:in `gsub'
  2. /home/michael/Research/LensKit/website/gems/jruby/1.9/gems/nanoc-3.6.5/lib/nanoc/cli/stream_cleaners/utf8.rb:11:in `clean'
  3. /home/michael/Research/LensKit/website/gems/jruby/1.9/gems/nanoc-3.6.5/lib/nanoc/cli/cleaning_stream.rb:115:in `clean'
  4. org/jruby/RubyArray.java:1617:in `each'
  5. org/jruby/RubyEnumerable.java:815:in `inject'
  6. /home/michael/Research/LensKit/website/gems/jruby/1.9/gems/nanoc-3.6.5/lib/nanoc/cli/cleaning_stream.rb:115:in `clean'
  7. /home/michael/Research/LensKit/website/gems/jruby/1.9/gems/nanoc-3.6.5/lib/nanoc/cli/cleaning_stream.rb:44:in `write'
  8. org/jruby/RubyKernel.java:1361:in `warn'
  9. file:/home/michael/Research/LensKit/website/jruby-1.7.4/lib/jruby.jar!/jruby/kernel/signal.rb:27:in `trap'
  ... 15 more lines omitted. See full crash log for details.

If you believe this is a bug in nanoc, please do report it at
-> https://github.com/nanoc/nanoc/issues/new <-

A detailed crash log has been written to ./crash.log.
```

Running with `LANG=en_US.UTF-8` makes it go away.

**Comment by ddfreyne** [comment]
The [character encoding section on the Troubleshooting page](http://nanoc.ws/docs/troubleshooting/#character-encoding-issues) should cover this now.
