### ISSUE TITLE
When deploying: TypeError: incompatible marshal file format (can't be read) 	format version 4.8 required; 60.60 given

### ISSUE THREAD

**Issue by gtheys** [nanoc/nanoc#409]
I try to deploy to the server and got this error:

EDIT: when I run any nanoc command inside a existing nanoc project. When I create a new project I don't have a problem.
EDIT2: Al versions are the same: ruby, gems, nanoc, etc. So I'm certain it's has to do with my site content. 

> TypeError: incompatible marshal file format (can't be read)
>   format version 4.8 required; 60.60 given

```
Crashlog created at 2014-03-31 14:28:03 +0200

===== MESSAGE:

TypeError: incompatible marshal file format (can't be read)
    format version 4.8 required; 60.60 given

===== COMPILATION STACK:

  (empty)

===== STACK TRACE:

  0. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/pstore.rb:475:in `load'
  1. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/pstore.rb:475:in `load'
  2. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/pstore.rb:410:in `load_data'
  3. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/pstore.rb:327:in `transaction'
  4. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/base/store.rb:76:in `load'
  5. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/base/compilation/compiler.rb:127:in `block in load'
  6. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/base/compilation/compiler.rb:127:in `each'
  7. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/base/compilation/compiler.rb:127:in `load'
  8. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/base/source_data/site.rb:250:in `load'
  9. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/cli/command_runner.rb:63:in `load_site'
  10. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/cli/commands/deploy.rb:20:in `run'
  11. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/cli/command_runner.rb:14:in `block in call'
  12. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/cli/error_handler.rb:70:in `handle_while'
  13. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/cli/error_handler.rb:26:in `handle_while'
  14. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/cli/command_runner.rb:13:in `call'
  15. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cri-2.5.0/lib/cri/command_dsl.rb:185:in `block in runner'
  16. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cri-2.5.0/lib/cri/command.rb:298:in `call'
  17. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cri-2.5.0/lib/cri/command.rb:298:in `run_this'
  18. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cri-2.5.0/lib/cri/command.rb:251:in `run'
  19. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cri-2.5.0/lib/cri/command.rb:264:in `run'
  20. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/cli.rb:59:in `block in run'
  21. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/cli/error_handler.rb:70:in `handle_while'
  22. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/cli/error_handler.rb:26:in `handle_while'
  23. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib/nanoc/cli.rb:57:in `run'
  24. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/bin/nanoc:19:in `<top (required)>'
  25. /Users/gtheys/.rbenv/versions/2.0.0-p247/bin/nanoc:23:in `load'

===== VERSION INFORMATION:

nanoc 3.6.8 © 2007-2013 Denis Defreyne.
Running ruby 2.0.0 (2013-06-27) on x86_64-darwin13.0.0 with RubyGems 2.2.2.

===== SYSTEM INFORMATION:

Darwin geerts-macbook.telenet.be 13.1.0 Darwin Kernel Version 13.1.0: Thu Jan 16 19:40:37 PST 2014; root:xnu-2422.90.20~2/RELEASE_X86_64 x86_64

===== INSTALLED GEMS:

  adsf 1.2.0
  builder 3.2.2
  bundler 1.3.5
  celluloid 0.15.2
  celluloid-io 0.15.0
  coderay 1.1.0
  colored 1.2
  commonjs 0.2.7
  cri 2.5.0
  em-websocket 0.5.0
  eventmachine 1.0.3
  ffi 1.9.3
  formatador 0.2.4
  fssm 0.2.10
  growl 1.0.3
  guard 2.6.0
  guard-bundler 2.0.0
  guard-livereload 2.1.2
  guard-nanoc 1.0.2
  guard-pow 2.0.0
  haml 4.0.5
  http_parser.rb 0.5.3
  i18n 0.6.9
  kramdown 1.3.3
  less 2.5.0
  listen 2.7.1
  lumberjack 1.0.5
  method_source 0.8.2
  mime-types 2.2
  mini_portile 0.5.3
  multi_json 1.9.2
  nanoc 3.6.8
  nio4r 1.0.0
  nokogiri 1.6.1
  pry 0.9.12.6
  rack 1.5.2
  rack-rewrite 1.5.0
  rake 10.2.0
  rb-fsevent 0.9.4
  rb-inotify 0.9.3
  rb-readline 0.5.1
  redcarpet 3.1.1
  sass 3.3.4
  slop 3.5.0
  systemu 2.6.4
  thor 0.19.1
  tilt 2.0.1
  timers 1.1.0

===== ENVIRONMENT:

Apple_PubSub_Socket_Render => "/tmp/launch-Lllxg0/Render"
BUNDLE_BIN_PATH => "/Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/bin/bundle"
BUNDLE_GEMFILE => "/Users/gtheys/Code/bitless/Gemfile"
BUNDLE_ORIG_MANPATH => "/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:"
CLICOLOR => "true"
COLORFGBG => "11;15"
CZSH => "/Users/gtheys/.dotfiles"
EDITOR => "subl"
GEM_HOME => "/Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0"
GEM_PATH => "/Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0:/Users/gtheys/.gem/ruby/2.0.0"
GREP_COLOR => "1;32"
GREP_OPTIONS => "--exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --color=auto"
HOME => "/Users/gtheys"
ITERM_PROFILE => "Default"
ITERM_SESSION_ID => "w0t1p0"
LC_CTYPE => ""
LESS => "-R"
LOGNAME => "gtheys"
LSCOLORS => "exfxcxdxbxegedabagacad"
MANPATH => "/Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/kramdown-1.3.3/man:/usr/local/man:/usr/local/mysql/man:/usr/local/git/man"
PAGER => "less"
PATH => "/Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bin:/Users/gtheys/.rbenv/versions/2.0.0-p247/bin:/usr/local/Cellar/rbenv/0.4.0/libexec:/Users/gtheys/.rbenv/plugins/rbenv-gemset/bin:/Users/gtheys/.rbenv/shims:./bin:/usr/local/bin:/usr/local/sbin:/Users/gtheys/.sfs:/Users/gtheys/.dotfiles/bin:/usr/bin:/bin:/usr/sbin:/sbin"
PROJECTS => "/Users/gtheys/Code"
PROMPT => "\n$(rb_prompt)in $(directory_name) $(git_dirty)$(need_push)\n\xE2\x80\xBA "
PWD => "/Users/gtheys/Code/bitless"
RBENV_DIR => "/Users/gtheys/Code/bitless"
RBENV_GEMSET_ALREADY => "yes"
RBENV_HOOK_PATH => ":/Users/gtheys/.rbenv/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks:/Users/gtheys/.rbenv/plugins/rbenv-gemset/etc/rbenv.d"
RBENV_ROOT => "/Users/gtheys/.rbenv"
RBENV_VERSION => "2.0.0-p247"
RPROMPT => "%{\e[01;36m%}%{\e[00m%}"
RUBYOPT => "-I/Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib -rbundler/setup"
SECURITYSESSIONID => "186a4"
SHELL => "/bin/zsh"
SHLVL => "1"
SSH_AUTH_SOCK => "/tmp/launch-7V0tlb/Listeners"
TERM => "xterm"
TERM_PROGRAM => "iTerm.app"
TMPDIR => "/var/folders/gf/10flxlps5kbbvy650c8b951m0000gn/T/"
USER => "gtheys"
ZSH => "/Users/gtheys/.oh-my-zsh"
__CF_USER_TEXT_ENCODING => "0x1F5:0:0"
__CHECKFIX1436934 => "1"

===== GEMFILE.LOCK:

GEM
  remote: http://rubygems.org/
  specs:
    adsf (1.2.0)
      rack (>= 1.0.0)
    builder (3.2.2)
    celluloid (0.15.2)
      timers (~> 1.1.0)
    celluloid-io (0.15.0)
      celluloid (>= 0.15.0)
      nio4r (>= 0.5.0)
    coderay (1.1.0)
    colored (1.2)
    commonjs (0.2.7)
    cri (2.5.0)
      colored (~> 1.2)
    em-websocket (0.5.0)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.5.3)
    eventmachine (1.0.3)
    ffi (1.9.3)
    formatador (0.2.4)
    fssm (0.2.10)
    growl (1.0.3)
    guard (2.6.0)
      formatador (>= 0.2.4)
      listen (~> 2.7)
      lumberjack (~> 1.0)
      pry (>= 0.9.12)
      thor (>= 0.18.1)
    guard-bundler (2.0.0)
      bundler (~> 1.0)
      guard (~> 2.2)
    guard-livereload (2.1.2)
      em-websocket (~> 0.5)
      guard (~> 2.0)
      multi_json (~> 1.8)
    guard-nanoc (1.0.2)
      guard (>= 1.8.0)
      nanoc (>= 3.6.3)
    guard-pow (2.0.0)
      guard (~> 2.0)
    haml (4.0.5)
      tilt
    http_parser.rb (0.5.3)
    i18n (0.6.9)
    kramdown (1.3.3)
    less (2.5.0)
      commonjs (~> 0.2.7)
    listen (2.7.1)
      celluloid (>= 0.15.2)
      celluloid-io (>= 0.15.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    lumberjack (1.0.5)
    method_source (0.8.2)
    mime-types (2.2)
    mini_portile (0.5.3)
    multi_json (1.9.2)
    nanoc (3.6.8)
      cri (~> 2.3)
    nio4r (1.0.0)
    nokogiri (1.6.1)
      mini_portile (~> 0.5.0)
    pry (0.9.12.6)
      coderay (~> 1.0)
      method_source (~> 0.8)
      slop (~> 3.4)
    rack (1.5.2)
    rack-rewrite (1.5.0)
    rake (10.2.0)
    rb-fsevent (0.9.4)
    rb-inotify (0.9.3)
      ffi (>= 0.5.0)
    rb-readline (0.5.1)
    redcarpet (3.1.1)
    sass (3.3.4)
    slop (3.5.0)
    systemu (2.6.4)
    thor (0.19.1)
    tilt (2.0.1)
    timers (1.1.0)

PLATFORMS
  ruby

DEPENDENCIES
  adsf (~> 1.2.0)
  builder
  bundler
  coderay
  fssm
  growl
  guard
  guard-bundler
  guard-livereload
  guard-nanoc
  guard-pow
  haml
  i18n
  kramdown (~> 1.3.3)
  less
  mime-types
  nanoc (~> 3.6.8)
  nokogiri
  pry
  rack
  rack-rewrite
  rake
  rb-fsevent
  rb-readline
  redcarpet
  sass
  systemu

===== LOAD PATHS:

  0. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib
  1. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/systemu-2.6.4/lib
  2. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sass-3.3.4/lib
  3. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/redcarpet-3.1.1/../../extensions/x86_64-darwin-13/2.0.0-static/redcarpet-3.1.1
  4. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/redcarpet-3.1.1/lib
  5. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rb-readline-0.5.1/lib
  6. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rack-rewrite-1.5.0/lib
  7. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.1/../../extensions/x86_64-darwin-13/2.0.0-static/nokogiri-1.6.1
  8. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nokogiri-1.6.1/lib
  9. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/mini_portile-0.5.3/lib
  10. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/mime-types-2.2/lib
  11. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/less-2.5.0/lib
  12. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/kramdown-1.3.3/lib
  13. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/i18n-0.6.9/lib
  14. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/haml-4.0.5/lib
  15. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/tilt-2.0.1/lib
  16. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/guard-pow-2.0.0/lib
  17. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/guard-nanoc-1.0.2/lib
  18. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nanoc-3.6.8/lib
  19. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/guard-livereload-2.1.2/lib
  20. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/multi_json-1.9.2/lib
  21. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/guard-bundler-2.0.0/lib
  22. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/guard-2.6.0/lib
  23. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib
  24. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/pry-0.9.12.6/lib
  25. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/slop-3.5.0/lib
  26. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/method_source-0.8.2/lib
  27. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/lumberjack-1.0.5/lib
  28. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/listen-2.7.1/lib
  29. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rb-inotify-0.9.3/lib
  30. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rb-fsevent-0.9.4/lib
  31. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/growl-1.0.3/lib
  32. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fssm-0.2.10/lib
  33. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/formatador-0.2.4/lib
  34. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/ffi-1.9.3/../../extensions/x86_64-darwin-13/2.0.0-static/ffi-1.9.3
  35. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/ffi-1.9.3/lib
  36. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/ffi-1.9.3/ext/ffi_c
  37. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/em-websocket-0.5.0/lib
  38. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/http_parser.rb-0.5.3/../../extensions/x86_64-darwin-13/2.0.0-static/http_parser.rb-0.5.3
  39. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/http_parser.rb-0.5.3/lib
  40. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/../../extensions/x86_64-darwin-13/2.0.0-static/eventmachine-1.0.3
  41. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib
  42. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cri-2.5.0/lib
  43. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commonjs-0.2.7/lib
  44. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/colored-1.2/lib
  45. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/coderay-1.1.0/lib
  46. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-io-0.15.0/lib
  47. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nio4r-1.0.0/../../extensions/x86_64-darwin-13/2.0.0-static/nio4r-1.0.0
  48. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/nio4r-1.0.0/lib
  49. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib
  50. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/timers-1.1.0/lib
  51. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/builder-3.2.2/lib
  52. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/adsf-1.2.0/lib
  53. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib
  54. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.2.0/lib
  55. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib
  56. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/site_ruby/2.0.0
  57. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/site_ruby/2.0.0/x86_64-darwin13.0.0
  58. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/site_ruby
  59. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/vendor_ruby/2.0.0
  60. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin13.0.0
  61. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/vendor_ruby
  62. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0
  63. /Users/gtheys/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/x86_64-darwin13.0.0
```

**Comment by strand** [comment]
☝️ I believe @ddfreyne meant #418 resolves the issue.

**Comment by ddfreyne** [comment]
@strand Correct—my previous comment indeed meant to say #418 rather than #409!
