### ISSUE TITLE
Cannot run rubocop after nanoc with rake

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#838]
I like to handle my nanoc builds with rake. Before and after `nanoc compile` runs there might be more things to do like running rubocop, haml_lint etc.

I found that `Nanoc::CLI::CleaningStream` leaks after running the nanoc task:
```ruby
require 'nanoc'
require 'nanoc/cli'

task :nanoc do
  Nanoc::CLI.run %w(compile)
end
```

The first indication is that my rake "progress report" (that print task names in blue) no longer outputs colors after the nanoc task completed. Another indication is the exception trace below.

Could you please elaborate why the cleaning stream infrastructure exists? I don't know any other tool that does something like it and I'm not sure what it's supposed to do other than printing typographic quotation marks etc. Is there a way to disable it?

Output:
```
$ bundle exec rake nanoc rubocop

[nanoc]       # printed blue
Loading site… done
Compiling site…

Site compiled in 1.17s.

[rubocop]     # printed without colors
Running RuboCop...
Inspecting 38 files
C.C...CCWWWW.CCCCC.CC..C...C......CCC.

Offenses:

private method `printf' called for #<Nanoc::CLI::CleaningStream:0x00000006afdd58>
["C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/formatter/clang_style_formatter.rb:12:in `block in report_file'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/formatter/clang_style_formatter.rb:11:in `each'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/formatter/clang_style_formatter.rb:11:in `report_file'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/formatter/progress_formatter.rb:43:in `block in finished'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/formatter/progress_formatter.rb:42:in `each'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/formatter/progress_formatter.rb:42:in `finished'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/formatter/formatter_set.rb:30:in `block (3 levels) in <class:FormatterSet>'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/formatter/formatter_set.rb:30:in `each'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/formatter/formatter_set.rb:30:in `block (2 levels) in <class:FormatterSet>'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:68:in `inspect_files'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/runner.rb:35:in `run'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/cli.rb:30:in `run'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/rake_task.rb:49:in `run_cli'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/rake_task.rb:37:in `run_main_task'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/rake_task.rb:29:in `block (2 levels) in initialize'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:58:in `verbose'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.37.2/lib/rubocop/rake_task.rb:27:in `block in initialize'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-funnel-0.15.0.pre/lib/rake/funnel/integration/progress_report.rb:47:in `call'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-funnel-0.15.0.pre/lib/rake/funnel/integration/progress_report.rb:47:in `block (4 levels) in create_patch'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-funnel-0.15.0.pre/lib/rake/funnel/integration/progress_report.rb:47:in `call'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-funnel-0.15.0.pre/lib/rake/funnel/integration/progress_report.rb:47:in `block (4 levels) in create_patch'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-funnel-0.15.0.pre/lib/rake/funnel/tasks/timing.rb:88:in `call'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-funnel-0.15.0.pre/lib/rake/funnel/tasks/timing.rb:88:in `block (5 levels) in benchmark'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-funnel-0.15.0.pre/lib/rake/funnel/support/timing/statistics.rb:22:in `benchmark'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-funnel-0.15.0.pre/lib/rake/funnel/tasks/timing.rb:80:in `block (2 levels) in benchmark'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-funnel-0.15.0.pre/lib/rake/funnel/tasks/timing.rb:87:in `call'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-funnel-0.15.0.pre/lib/rake/funnel/tasks/timing.rb:87:in `block (4 levels) in benchmark'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'", "C:/Ruby/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'", "C:/Ruby/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'", "C:/Ruby/bin/rake:33:in `<main>'"]
```

**Comment by ddfreyne** [comment]
I suggest replacing

```ruby
task :nanoc do
  Nanoc::CLI.run %w(compile)
end
```

with

```ruby
task :nanoc do
  sh 'nanoc'
end
```

as it achieves the same thing, and doesn’t run the Nanoc CLI in an environment where it’s not intended (it works best when run in its own process that’s spawned from `bin/nanoc`).

* * *

The Nanoc CLI replaces `$stdout` with a `CleaningStream` that wraps `$stdout`, so that color codes and non-ASCII characters can be written to standard output, and filtered out in cases where they are not supported.

`CleaningStream` does not implement/forward all methods that are defined in `IO` unfortunately. `#printf` is a tricky one to implement properly, too.

The `CleaningStream` is conceptually a solid idea, but having to forward a ton of methods on `IO` is a pain and there’s often gaps. I see two alternatives:

* Wrapping standard out in `Nanoc::CLI.out` instead of `$stdout`, but that’s bound to lead to mistakes (and might leak Unicode or color codes).

* Modifying the code that generates color codes to be conditional, and prevent color codes from being outputted that way. I’m unsure how this technique could apply to preventing non-ASCII characters from leaking, however.

**Comment by agross** [comment]
Many thanks! I was using `Nanoc::CLI.run` since nanoc 3.x and never had an issue. I was wondering if using it was the recommended way of calling nanoc from rake. Obviously it wasn't.

> The Nanoc CLI replaces $stdout with a CleaningStream that wraps $stdout, so that color codes and non-ASCII characters can be written to standard output, and filtered out in cases where they are not supported.

Can you give me an example where stripping color codes or non-ASCII would be desired? The only thing I can think of is non-ttys (e.g. `nanoc compile > log.txt`).

**Comment by ddfreyne** [comment]
> Can you give me an example where stripping color codes or non-ASCII would be desired? The only thing I can think of is non-ttys (e.g. `nanoc compile > log.txt`).

Yup—Nanoc strips color codes when stdout is not a terminal, and it transforms non-ASCII characters when the inferred terminal encoding is not UTF-8.
