### ISSUE TITLE
Net::HTTPRetriableError not retried in checks

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#943]
The HTML and CSS checks fail on a `Net::HTTPRetriableError`. See https://github.com/nanoc/nanoc/issues/928#issuecomment-241677271.

### Crash log

```
  0. /usr/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
  1. /usr/lib/ruby/2.3.0/net/http/response.rb:129:in `value'
  2. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.2/lib/w3c_validators/validator.rb:88:in `send_request'
  3. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.2/lib/w3c_validators/validator.rb:85:in `send_request'
  4. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.2/lib/w3c_validators/markup_validator.rb:131:in `validate'
  5. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.2/lib/w3c_validators/markup_validator.rb:117:in `validate_file'
  6. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.3.0/lib/nanoc/extra/checking/checks/w3c_validator.rb:8:in `block in run'
  7. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.3.0/lib/nanoc/extra/checking/checks/w3c_validator.rb:7:in `each'
  8. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.3.0/lib/nanoc/extra/checking/checks/w3c_validator.rb:7:in `run'
  9. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.3.0/lib/nanoc/extra/checking/runner.rb:120:in `block in run_checks'
```

**Comment by ddfreyne** [comment]
@anton-tsyganenko @elomatreb This is unfortunately a bug in `w3c_validators` rather than Nanoc (see https://github.com/alexdunae/w3c_validators/issues/16). Either this bug gets fixed, or we switch the `html` and `css` checks to use a different implementation (e.g. [html-proofer](https://github.com/gjtorikian/html-proofer)).

**Comment by ddfreyne** [comment]
#965 is a PR which replaces the `w3c_validators` usage with Nokogiri. Unfortunately, Nokogiri’s validation mechanism is far weaker than that of `w3c_validators`…

**Comment by ddfreyne** [comment]
I’m going to close this issue for now, as the problem exists in w3c_validators and there is no good/easy alternative to w3c_validators.

FYI, for nanoc.ws I added vnu.jar and added a check that uses it: https://github.com/nanoc/nanoc.ws/commit/44ccc8b57dc826c259b68d65c814df2d3d403c8b

**Comment by ddfreyne** [comment]
Reopening as there’s an easy fix: add `validator_uri`:

```ruby
validator = MarkupValidator.new(:validator_uri => 'http://validator.w3.org/nu/')
```

**Comment by ddfreyne** [comment]
A proper fix is coming up: https://github.com/alexdunae/w3c_validators/pull/18. I’ll close this issue after all, as there’s no expected work from the Nanoc side of things.

**Comment by anton-tsyganenko** [comment]
Since there there were a lot of nanoc and w3c_validators updates, but it still crashes:
```
$ nanoc check -a
Loading site… done
  Running check css…              ok
  Running check external_links…   ok
  Running check html…             
Captain! We’ve been hit!

Message:

Net::HTTPRetriableError: 302 "Found"

Stack trace:

  0. /usr/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
  1. /usr/lib/ruby/2.3.0/net/http/response.rb:129:in `value'
  2. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.3.1/lib/w3c_validators/validator.rb:112:in `send_request'
  3. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.3.1/lib/w3c_validators/validator.rb:109:in `send_request'
  4. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.3.1/lib/w3c_validators/markup_validator.rb:131:in `valida
  5. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.3.1/lib/w3c_validators/markup_validator.rb:117:in `valida
  6. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.4.6/lib/nanoc/checking/checks/w3c_validator.rb:8:in `block in run'
  7. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.4.6/lib/nanoc/checking/checks/w3c_validator.rb:7:in `each'
  8. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.4.6/lib/nanoc/checking/checks/w3c_validator.rb:7:in `run'
  9. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.4.6/lib/nanoc/checking/runner.rb:120:in `block in run_checks'
  ... 20 more lines omitted. See full crash log for details.

If you believe this is a bug in Nanoc, please do report it at
-> https://github.com/nanoc/nanoc/issues/new <-

A detailed crash log has been written to ./crash.log.

```
I request re-opening.

**Comment by ddfreyne** [comment]
@anton-tsyganenko This is a bug in `w3c_validators` which is tracked by w3c-validators/w3c_validators#25. This is not a bug in Nanoc and there is, as far as I can tell, not much that Nanoc can do to fix or work around this problem.
