### ISSUE TITLE
Nanoc crashing when following tutorial

### ISSUE THREAD

**Issue by drhectapus** [nanoc/nanoc#953]
Following the nanoc tutorial: http://nanoc.ws/doc/tutorial/

After uncommenting:

```
#compile '/**/*.md' do
#  filter :kramdown
#  layout '/default.*'
#end
```

I am unable to run `nanoc`:

```
Loading site… done
Compiling site…

Captain! We’ve been hit!

Message:

Nanoc::Int::ItemRepRouter::IdenticalRoutesError: The item representations <Nanoc::Int::ItemRep name="default" binary=false raw_path="output/index.html" item.identifier="/index.html"> and <Nanoc::Int::ItemRep name="default" binary=false raw_path="" item.identifier="/index.md"> are both routed to /index.html.

Compilation stack:

  (empty)

Stack trace:

  0. /Users/Joseph/.rvm/gems/ruby-2.3.1/gems/nanoc-4.3.4/lib/nanoc/base/services/item_rep_router.rb:35:in `route_rep'
  1. /Users/Joseph/.rvm/gems/ruby-2.3.1/gems/nanoc-4.3.4/lib/nanoc/base/services/item_rep_router.rb:23:in `block (2 levels) in run'
  2. /Users/Joseph/.rvm/gems/ruby-2.3.1/gems/nanoc-4.3.4/lib/nanoc/base/services/item_rep_router.rb:22:in `each'
  3. /Users/Joseph/.rvm/gems/ruby-2.3.1/gems/nanoc-4.3.4/lib/nanoc/base/services/item_rep_router.rb:22:in `block in run'
  4. /Users/Joseph/.rvm/gems/ruby-2.3.1/gems/nanoc-4.3.4/lib/nanoc/base/compilation/item_rep_repo.rb:25:in `each'
  5. /Users/Joseph/.rvm/gems/ruby-2.3.1/gems/nanoc-4.3.4/lib/nanoc/base/compilation/item_rep_repo.rb:25:in `each'
  6. /Users/Joseph/.rvm/gems/ruby-2.3.1/gems/nanoc-4.3.4/lib/nanoc/base/services/item_rep_router.rb:20:in `run'
  7. /Users/Joseph/.rvm/gems/ruby-2.3.1/gems/nanoc-4.3.4/lib/nanoc/base/services/item_rep_builder.rb:19:in `run'
  8. /Users/Joseph/.rvm/gems/ruby-2.3.1/gems/nanoc-4.3.4/lib/nanoc/base/compilation/compiler.rb:133:in `build_reps'
  9. /Users/Joseph/.rvm/gems/ruby-2.3.1/gems/nanoc-4.3.4/lib/nanoc/base/compilation/compiler.rb:76:in `run_all'
  ... 23 more lines omitted. See full crash log for details.

If you believe this is a bug in Nanoc, please do report it at
-> https://github.com/nanoc/nanoc/issues/new <-

A detailed crash log has been written to ./crash.log.
```

I'm running:

```
[tutorial]$ nanoc -v
Nanoc 4.3.4 © 2007-2016 Denis Defreyne.
Running ruby 2.3.1 (2016-04-26) on x86_64-darwin16 with RubyGems 2.6.7.
```

**Comment by ddfreyne** [comment]
That happens when copying (rather than moving) `content/index.html` to `content/index.md`. Looks like you already figured it out though!
